source "https://rubygems.org"

ruby '2.7.3'

gem "capybara"
gem "selenium-webdriver"
gem 'rack'

group :development do
  gem "sinatra"
  gem "sinatra-contrib"
end

group :development, :test do
  gem "rspec"
end